app_identifier "com.mgacy.Adequate"

copyright "#{Time.now.year} Mathew Gacy"

app_rating_config_path "./fastlane/metadata/rating_config.json"

price_tier 0 # free app
#
# submission_information({
#     export_compliance_encryption_updated: false,
#     export_compliance_uses_encryption: false,
#     content_rights_contains_third_party_content: false,
#     add_id_info_uses_idfa: false
# })
#
# ipa("./fastlane/builds/Adequate.ipa")
#
# submit_for_review(true)
#
# automatic_release(false)
#
# force(true)
