# See the following for a list of all keys:
# https://docs.fastlane.tools/actions/snapshot/#parameters
# https://docs.fastlane.tools/getting-started/ios/screenshots/#advanced-snapshot

# A list of devices you want to take the screenshots from
# Requirements: https://help.apple.com/app-store-connect/#/devd274dd925
devices([
  # "iPhone SE (1st generation)",             # 4.0 inch
  # "iPhone SE (2nd generation)",             # 4.7 inch
  # "iPhone 8 Plus",                          # 5.5 inch - Required
  # "iPhone 11 Pro",                          # 5.8 inch
  "iPhone 11 Pro Max",                      # 6.5 inch - Required
  # "iPad Pro (12.9-inch) (2nd generation)",  # 12.9 inch - Required
  # "iPad Pro (12.9-inch) (4th generation)"   # 12.9 inch - Required
])

# languages([
#   "en-US",
#   "de-DE",
#   "it-IT",
#   ["pt", "pt_BR"] # Portuguese with Brazilian locale
# ])

# Path to the workspace file
# workspace("Adequate.xcworkspace")

# The name of the scheme which contains the UI Tests
# scheme("AdequateUITests")

# Where should the resulting screenshots be stored?
# output_directory("./screenshots")

# Clear all previously generated screenshots before creating new ones
# clear_previous_screenshots(true)

# Automatically override the status bar to show 9:41 AM, full battery, and full reception
override_status_bar(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# Don't open the HTML summary after running snapshot
skip_open_summary(true)

# Use dark mode
# dark_mode(true)

# For more information about all available options run
# fastlane action snapshot
